### ISSUE TITLE
Credentials/Secrets should never be committed to version control systems

### ISSUE THREAD

**Issue by GusGold** [MiloWardell/MFI-Signal-Analysis#1]
https://github.com/MiloWardell/MFI-Signal-Analysis/blob/f41008108acd5f1db1becdea6f9ee32b0b266e10/config.js#L17

**Comment by MiloWardell** [comment]
Changed to store in environment variable SQL_PASSWORD. Originally i did not thing this was an issue because the database was meant to be created and stored locally. Readme will also be updated.

`connection: {
    host: '127.0.0.1',
    user: 'root',
    password: process.env.SQL_PASSWORD,
    database: 'tickers'
  }`

**Comment by GusGold** [comment]
Of course, not an issue if it's just local, but a very good practise to get into. I'd also recommend chucking the user in a env variable too
