### ISSUE TITLE
'Not Enough Data' isn't very clear from a programatic point of view

### ISSUE THREAD

**Issue by GusGold** [MiloWardell/MFI-Signal-Analysis#2]
Avoid mixing datatypes in general

https://github.com/MiloWardell/MFI-Signal-Analysis/blob/f41008108acd5f1db1becdea6f9ee32b0b266e10/lib/MoneyFlowIndex.js#L24-L37

**Comment by MiloWardell** [comment]
Changed to: `MFI: 'Not Enough Candle Data - Period too large'`

**Comment by GusGold** [comment]
Was more focusing on that a string isn't an error. Perhaps you could use `new Error('Not enough data')`, but it'd be better from a programatic point of view to return `null` here, and instead log the error, or something along those lines.
