### ISSUE TITLE
Arrray lengths can't be less than 0, so checking for <= is a bit misleading

### ISSUE THREAD

**Issue by GusGold** [MiloWardell/MFI-Signal-Analysis#3]
https://github.com/MiloWardell/MFI-Signal-Analysis/blob/f41008108acd5f1db1becdea6f9ee32b0b266e10/lib/MoneyFlowIndex.js#L56

**Comment by MiloWardell** [comment]
changed logic to:
`if (!negative.length) return sum(positive) / 0.00001`
