### ISSUE TITLE
Dividing by a very small number will typically result in a large number.

### ISSUE THREAD

**Issue by GusGold** [MiloWardell/MFI-Signal-Analysis#4]
https://github.com/MiloWardell/MFI-Signal-Analysis/blob/f41008108acd5f1db1becdea6f9ee32b0b266e10/lib/MoneyFlowIndex.js#L56-L57

Is this intended functionallity, as it will affect the MoneyFlowIndex

https://github.com/MiloWardell/MFI-Signal-Analysis/blob/f41008108acd5f1db1becdea6f9ee32b0b266e10/lib/MoneyFlowIndex.js#L29-L32

**Comment by MiloWardell** [comment]
This is intended as if there is no negative price action in 14 days it should be taken as a strong overbought signal
